# Generated by Django 3.0.5 on 2020-11-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20201118_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoing_book',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='returned_book',
            old_name='book_id',
            new_name='book',
        ),
    ]
