# Generated by Django 3.0.5 on 2020-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_issued_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issued_book',
            name='return_date',
        ),
        migrations.AddField(
            model_name='issued_book',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
