# Generated by Django 3.0.5 on 2020-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20201120_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoing_book',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
