# Generated by Django 3.0.5 on 2020-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_ongoing_book_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoing_book',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
