# Generated by Django 3.0.5 on 2020-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_ongoing_book_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returned_book',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
