# Generated by Django 3.0.5 on 2020-11-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_file_issued_file_ongoing_file_returned_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued_file',
            old_name='book',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='ongoing_file',
            old_name='book',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='returned_file',
            old_name='book',
            new_name='file',
        ),
    ]
